[package]
name = "ascparse"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "0.17"

[dependencies]
lalrpop-util = "0.17"
regex = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nom = "5.0"
